import { app_color, blue0, blue6, light_green3, red0 } from "./color.utils";

export const FACEBOOK_APP_ID = "1258820975000118";
export const FACEBOOK_SECRET = "f3a33e37e1df45566db5bcf9c1eb64b4";

export const ERROR_MESSAGE = "Error occurred, please try again later";
export const LOAN_STATUS_PENDING = "Pending";
export const LOAN_STATUS_CANCELLED = "Cancelled";
export const LOAN_STATUS_AWAITING_GUARANTOR = "Awaiting Guarantor";
export const LOAN_STATUS_IN_REVIEW = "In Review";
export const LOAN_STATUS_APPROVED = "Approved";
export const LOAN_STATUS_DISBURSED = "Disbursed";
export const LOAN_STATUS_REPAYMENT_DUE = "Repayment Due";
export const LOAN_STATUS_PARTLY_REPAID = "Partly Repaid";
export const LOAN_STATUS_FULL_REPAID = "Full Repaid";
export const LOAN_STATUS_DECLINED = "Declined";
export const WIDTH = "width";
export const HEIGHT = "height";

export const filterPending = "Pending";
export const filterApproved = "Active";
export const filterFull = "Full";
export const filterDisabled = "Closed";
export const filterDisapproved = "Disapproved";

export const DEFAULT_COUNTRY = "defaultCountry";
export const DEFAULT_STATE = "defaultState";
export const DEFAULT_REGION = "defaultRegion";

export const WORDS = "words";
export const WORD_LIST = "wordList";
export const ALL_SEARCHES = "allSearches";
export const SEARCH_LIST = "searchList";

export const SPACE = "____";

export const SHOW_PHONE = "showPhone";
export const SHOW_EMAIL = "showEmail";
export const PRIVATE_PROFILE = "privateProfile";
export const PRIVATE_CHAT = "privateChat";
export const SHOW_PREF = "showPref";
export const SHOW_SPLIT = "showSplit";
export const SPLIT_PREF = "splitPref";

export const SAMPLE_TYPE_DISAPPROVED_PROFILES = 0;
export const SAMPLE_TYPE_DISAPPROVED_REVIEWS = 1;
export const SAMPLE_TYPE_REPORT_PROFILE = 2;
export const SAMPLE_TYPE_REPORT_GROUPS = 3;
export const SAMPLE_TYPE_REPORT_REVIEWS = 4;

export const LAST_READ_NOTIFY_TIME = "lastReadNotifyTime";

export const sortOrders = ["Relevance", "Lowest Price", "Highest Price", "Newest"];

export const filterKeysJoined = [filterApproved, filterFull, filterDisabled];
export const filterKeys = [
  filterPending,
  filterApproved,
  filterFull,
  filterDisabled,
  filterDisapproved,
];
export const filterColors = ["light_green3", "blue0", "app_color", "blue6", "red0"];

export const states = [
  {
    state: {
      name: "Abia State",
      id: 1,
      locals: [
        { name: "Aba South", id: 1 },
        { name: "Arochukwu", id: 2 },
        { name: "Bende", id: 3 },
        { name: "Ikwuano", id: 4 },
        { name: "Isiala Ngwa North", id: 5 },
        { name: "Isiala Ngwa South", id: 6 },
        { name: "Isuikwuato", id: 7 },
        { name: "Obi Ngwa", id: 8 },
        { name: "Ohafia", id: 9 },
        { name: "Osisioma", id: 10 },
        { name: "Ugwunagbo", id: 11 },
        { name: "Ukwa East", id: 12 },
        { name: "Ukwa West", id: 13 },
        { name: "Umuahia North", id: 14 },
        { name: "Umuahia South", id: 15 },
        { name: "Umu Nneochi", id: 16 },
      ],
    },
  },
  {
    state: {
      name: "Adamawa State",
      id: 2,
      locals: [
        { name: "Fufure", id: 1 },
        { name: "Ganye", id: 2 },
        { name: "Gayuk", id: 3 },
        { name: "Gombi", id: 4 },
        { name: "Grie", id: 5 },
        { name: "Hong", id: 6 },
        { name: "Jada", id: 7 },
        { name: "Lamurde", id: 8 },
        { name: "Madagali", id: 9 },
        { name: "Maiha", id: 10 },
        { name: "Mayo Belwa", id: 11 },
        { name: "Michika", id: 12 },
        { name: "Mubi North", id: 13 },
        { name: "Mubi South", id: 14 },
        { name: "Numan", id: 15 },
        { name: "Shelleng", id: 16 },
        { name: "Song", id: 17 },
        { name: "Toungo", id: 18 },
        { name: "Yola North", id: 19 },
        { name: "Yola South", id: 20 },
      ],
    },
  },
  {
    state: {
      name: "Akwa Ibom State",
      id: 3,
      locals: [
        { name: "Eastern Obolo", id: 1 },
        { name: "Eket", id: 2 },
        { name: "Esit Eket", id: 3 },
        { name: "Essien Udim", id: 4 },
        { name: "Etim Ekpo", id: 5 },
        { name: "Etinan", id: 6 },
        { name: "Ibeno", id: 7 },
        { name: "Ibesikpo Asutan", id: 8 },
        { name: "Ibiono-Ibom", id: 9 },
        { name: "Ika", id: 10 },
        { name: "Ikono", id: 11 },
        { name: "Ikot Abasi", id: 12 },
        { name: "Ikot Ekpene", id: 13 },
        { name: "Ini", id: 14 },
        { name: "Itu", id: 15 },
        { name: "Mbo", id: 16 },
        { name: "Mkpat-Enin", id: 17 },
        { name: "Nsit-Atai", id: 18 },
        { name: "Nsit-Ibom", id: 19 },
        { name: "Nsit-Ubium", id: 20 },
        { name: "Obot Akara", id: 21 },
        { name: "Okobo", id: 22 },
        { name: "Onna", id: 23 },
        { name: "Oron", id: 24 },
        { name: "Oruk Anam", id: 25 },
        { name: "Udung-Uko", id: 26 },
        { name: "Ukanafun", id: 27 },
        { name: "Uruan", id: 28 },
        { name: "Urue-Offong/Oruko", id: 29 },
        { name: "Uyo", id: 30 },
      ],
    },
  },
  {
    state: {
      name: "Anambra State",
      id: 4,
      locals: [
        { name: "Anambra East", id: 1 },
        { name: "Anambra West", id: 2 },
        { name: "Anaocha", id: 3 },
        { name: "Awka North", id: 4 },
        { name: "Awka South", id: 5 },
        { name: "Ayamelum", id: 6 },
        { name: "Dunukofia", id: 7 },
        { name: "Ekwusigo", id: 8 },
        { name: "Idemili North", id: 9 },
        { name: "Idemili South", id: 10 },
        { name: "Ihiala", id: 11 },
        { name: "Njikoka", id: 12 },
        { name: "Nnewi North", id: 13 },
        { name: "Nnewi South", id: 14 },
        { name: "Ogbaru", id: 15 },
        { name: "Onitsha North", id: 16 },
        { name: "Onitsha South", id: 17 },
        { name: "Orumba North", id: 18 },
        { name: "Orumba South", id: 19 },
        { name: "Oyi", id: 20 },
      ],
    },
  },
  {
    state: {
      name: "Bauchi State",
      id: 5,
      locals: [
        { name: "Bauchi", id: 1 },
        { name: "Bogoro", id: 2 },
        { name: "Damban", id: 3 },
        { name: "Darazo", id: 4 },
        { name: "Dass", id: 5 },
        { name: "Gamawa", id: 6 },
        { name: "Ganjuwa", id: 7 },
        { name: "Giade", id: 8 },
        { name: "Itas/Gadau", id: 9 },
        { name: "Jama'are", id: 10 },
        { name: "Katagum", id: 11 },
        { name: "Kirfi", id: 12 },
        { name: "Misau", id: 13 },
        { name: "Ningi", id: 14 },
        { name: "Shira", id: 15 },
        { name: "Tafawa Balewa", id: 16 },
        { name: "Toro", id: 17 },
        { name: "Warji", id: 18 },
        { name: "Zaki", id: 19 },
      ],
    },
  },
  {
    state: {
      name: "Bayelsa State",
      id: 6,
      locals: [
        { name: "Ekeremor", id: 1 },
        { name: "Kolokuma/Opokuma", id: 2 },
        { name: "Nembe", id: 3 },
        { name: "Ogbia", id: 4 },
        { name: "Sagbama", id: 5 },
        { name: "Southern Ijaw", id: 6 },
        { name: "Yenagoa", id: 7 },
      ],
    },
  },
  {
    state: {
      name: "Benue State",
      id: 7,
      locals: [
        { name: "Apa", id: 1 },
        { name: "Ado", id: 2 },
        { name: "Buruku", id: 3 },
        { name: "Gboko", id: 4 },
        { name: "Guma", id: 5 },
        { name: "Gwer East", id: 6 },
        { name: "Gwer West", id: 7 },
        { name: "Katsina-Ala", id: 8 },
        { name: "Konshisha", id: 9 },
        { name: "Kwande", id: 10 },
        { name: "Logo", id: 11 },
        { name: "Makurdi", id: 12 },
        { name: "Obi", id: 13 },
        { name: "Ogbadibo", id: 14 },
        { name: "Ohimini", id: 15 },
        { name: "Oju", id: 16 },
        { name: "Okpokwu", id: 17 },
        { name: "Oturkpo", id: 18 },
        { name: "Tarka", id: 19 },
        { name: "Ukum", id: 20 },
        { name: "Ushongo", id: 21 },
        { name: "Vandeikya", id: 22 },
      ],
    },
  },
  {
    state: {
      name: "Borno State",
      id: 8,
      locals: [
        { name: "Askira/Uba", id: 1 },
        { name: "Bama", id: 2 },
        { name: "Bayo", id: 3 },
        { name: "Biu", id: 4 },
        { name: "Chibok", id: 5 },
        { name: "Damboa", id: 6 },
        { name: "Dikwa", id: 7 },
        { name: "Gubio", id: 8 },
        { name: "Guzamala", id: 9 },
        { name: "Gwoza", id: 10 },
        { name: "Hawul", id: 11 },
        { name: "Jere", id: 12 },
        { name: "Kaga", id: 13 },
        { name: "Kala/Balge", id: 14 },
        { name: "Konduga", id: 15 },
        { name: "Kukawa", id: 16 },
        { name: "Kwaya Kusar", id: 17 },
        { name: "Mafa", id: 18 },
        { name: "Magumeri", id: 19 },
        { name: "Maiduguri", id: 20 },
        { name: "Marte", id: 21 },
        { name: "Mobbar", id: 22 },
        { name: "Monguno", id: 23 },
        { name: "Ngala", id: 24 },
        { name: "Nganzai", id: 25 },
        { name: "Shani", id: 26 },
      ],
    },
  },
  {
    state: {
      name: "Cross River State",
      id: 9,
      locals: [
        { name: "Akamkpa", id: 1 },
        { name: "Akpabuyo", id: 2 },
        { name: "Bakassi", id: 3 },
        { name: "Bekwarra", id: 4 },
        { name: "Biase", id: 5 },
        { name: "Boki", id: 6 },
        { name: "Calabar Municipal", id: 7 },
        { name: "Calabar South", id: 8 },
        { name: "Etung", id: 9 },
        { name: "Ikom", id: 10 },
        { name: "Obanliku", id: 11 },
        { name: "Obubra", id: 12 },
        { name: "Obudu", id: 13 },
        { name: "Odukpani", id: 14 },
        { name: "Ogoja", id: 15 },
        { name: "Yakuur", id: 16 },
        { name: "Yala", id: 17 },
      ],
    },
  },
  {
    state: {
      name: "Delta State",
      id: 10,
      locals: [
        { name: "Aniocha South", id: 1 },
        { name: "Bomadi", id: 2 },
        { name: "Burutu", id: 3 },
        { name: "Ethiope East", id: 4 },
        { name: "Ethiope West", id: 5 },
        { name: "Ika North East", id: 6 },
        { name: "Ika South", id: 7 },
        { name: "Isoko North", id: 8 },
        { name: "Isoko South", id: 9 },
        { name: "Ndokwa East", id: 10 },
        { name: "Ndokwa West", id: 11 },
        { name: "Okpe", id: 12 },
        { name: "Oshimili North", id: 13 },
        { name: "Oshimili South", id: 14 },
        { name: "Patani", id: 15 },
        { name: "Sapele", id: 16 },
        { name: "Udu", id: 17 },
        { name: "Ughelli North", id: 18 },
        { name: "Ughelli South", id: 19 },
        { name: "Ukwuani", id: 20 },
        { name: "Uvwie", id: 21 },
        { name: "Warri North", id: 22 },
        { name: "Warri South", id: 23 },
        { name: "Warri South West", id: 24 },
      ],
    },
  },
  {
    state: {
      name: "Ebonyi State",
      id: 11,
      locals: [
        { name: "Afikpo North", id: 1 },
        { name: "Afikpo South", id: 2 },
        { name: "Ebonyi", id: 3 },
        { name: "Ezza North", id: 4 },
        { name: "Ezza South", id: 5 },
        { name: "Ikwo", id: 6 },
        { name: "Ishielu", id: 7 },
        { name: "Ivo", id: 8 },
        { name: "Izzi", id: 9 },
        { name: "Ohaozara", id: 10 },
        { name: "Ohaukwu", id: 11 },
        { name: "Onicha", id: 12 },
      ],
    },
  },
  {
    state: {
      name: "Edo State",
      id: 12,
      locals: [
        { name: "Egor", id: 1 },
        { name: "Esan Central", id: 2 },
        { name: "Esan North-East", id: 3 },
        { name: "Esan South-East", id: 4 },
        { name: "Esan West", id: 5 },
        { name: "Etsako Central", id: 6 },
        { name: "Etsako East", id: 7 },
        { name: "Etsako West", id: 8 },
        { name: "Igueben", id: 9 },
        { name: "Ikpoba Okha", id: 10 },
        { name: "Orhionmwon", id: 11 },
        { name: "Oredo", id: 12 },
        { name: "Ovia North-East", id: 13 },
        { name: "Ovia South-West", id: 14 },
        { name: "Owan East", id: 15 },
        { name: "Owan West", id: 16 },
        { name: "Uhunmwonde", id: 17 },
      ],
    },
  },
  {
    state: {
      name: "Ekiti State",
      id: 13,
      locals: [
        { name: "Efon", id: 1 },
        { name: "Ekiti East", id: 2 },
        { name: "Ekiti South-West", id: 3 },
        { name: "Ekiti West", id: 4 },
        { name: "Emure", id: 5 },
        { name: "Gbonyin", id: 6 },
        { name: "Ido Osi", id: 7 },
        { name: "Ijero", id: 8 },
        { name: "Ikere", id: 9 },
        { name: "Ikole", id: 10 },
        { name: "Ilejemeje", id: 11 },
        { name: "Irepodun/Ifelodun", id: 12 },
        { name: "Ise/Orun", id: 13 },
        { name: "Moba", id: 14 },
        { name: "Oye", id: 15 },
      ],
    },
  },
  {
    state: {
      name: "Enugu State",
      id: 14,
      locals: [
        { name: "Awgu", id: 1 },
        { name: "Enugu East", id: 2 },
        { name: "Enugu North", id: 3 },
        { name: "Enugu South", id: 4 },
        { name: "Ezeagu", id: 5 },
        { name: "Igbo Etiti", id: 6 },
        { name: "Igbo Eze North", id: 7 },
        { name: "Igbo Eze South", id: 8 },
        { name: "Isi Uzo", id: 9 },
        { name: "Nkanu East", id: 10 },
        { name: "Nkanu West", id: 11 },
        { name: "Nsukka", id: 12 },
        { name: "Oji River", id: 13 },
        { name: "Udenu", id: 14 },
        { name: "Udi", id: 15 },
        { name: "Uzo Uwani", id: 16 },
      ],
    },
  },
  {
    state: {
      name: "FCT",
      id: 15,
      locals: [
        { name: "Bwari", id: 1 },
        { name: "Gwagwalada", id: 2 },
        { name: "Kuje", id: 3 },
        { name: "Kwali", id: 4 },
        { name: "Municipal Area Council", id: 5 },
      ],
    },
  },
  {
    state: {
      name: "Gombe State",
      id: 16,
      locals: [
        { name: "Balanga", id: 1 },
        { name: "Billiri", id: 2 },
        { name: "Dukku", id: 3 },
        { name: "Funakaye", id: 4 },
        { name: "Gombe", id: 5 },
        { name: "Kaltungo", id: 6 },
        { name: "Kwami", id: 7 },
        { name: "Nafada", id: 8 },
        { name: "Shongom", id: 9 },
        { name: "Yamaltu/Deba", id: 10 },
      ],
    },
  },
  {
    state: {
      name: "Imo State",
      id: 17,
      locals: [
        { name: "Ahiazu Mbaise", id: 1 },
        { name: "Ehime Mbano", id: 2 },
        { name: "Ezinihitte", id: 3 },
        { name: "Ideato North", id: 4 },
        { name: "Ideato South", id: 5 },
        { name: "Ihitte/Uboma", id: 6 },
        { name: "Ikeduru", id: 7 },
        { name: "Isiala Mbano", id: 8 },
        { name: "Isu", id: 9 },
        { name: "Mbaitoli", id: 10 },
        { name: "Ngor Okpala", id: 11 },
        { name: "Njaba", id: 12 },
        { name: "Nkwerre", id: 13 },
        { name: "Nwangele", id: 14 },
        { name: "Obowo", id: 15 },
        { name: "Oguta", id: 16 },
        { name: "Ohaji/Egbema", id: 17 },
        { name: "Okigwe", id: 18 },
        { name: "Orlu", id: 19 },
        { name: "Orsu", id: 20 },
        { name: "Oru East", id: 21 },
        { name: "Oru West", id: 22 },
        { name: "Owerri Municipal", id: 23 },
        { name: "Owerri North", id: 24 },
        { name: "Owerri West", id: 25 },
        { name: "Unuimo", id: 26 },
      ],
    },
  },
  {
    state: {
      name: "Jigawa State",
      id: 18,
      locals: [
        { name: "Babura", id: 1 },
        { name: "Biriniwa", id: 2 },
        { name: "Birnin Kudu", id: 3 },
        { name: "Buji", id: 4 },
        { name: "Dutse", id: 5 },
        { name: "Gagarawa", id: 6 },
        { name: "Garki", id: 7 },
        { name: "Gumel", id: 8 },
        { name: "Guri", id: 9 },
        { name: "Gwaram", id: 10 },
        { name: "Gwiwa", id: 11 },
        { name: "Hadejia", id: 12 },
        { name: "Jahun", id: 13 },
        { name: "Kafin Hausa", id: 14 },
        { name: "Kazaure", id: 15 },
        { name: "Kiri Kasama", id: 16 },
        { name: "Kiyawa", id: 17 },
        { name: "Kaugama", id: 18 },
        { name: "Maigatari", id: 19 },
        { name: "Malam Madori", id: 20 },
        { name: "Miga", id: 21 },
        { name: "Ringim", id: 22 },
        { name: "Roni", id: 23 },
        { name: "Sule Tankarkar", id: 24 },
        { name: "Taura", id: 25 },
        { name: "Yankwashi", id: 26 },
      ],
    },
  },
  {
    state: {
      name: "Kaduna State",
      id: 19,
      locals: [
        { name: "Chikun", id: 1 },
        { name: "Giwa", id: 2 },
        { name: "Igabi", id: 3 },
        { name: "Ikara", id: 4 },
        { name: "Jaba", id: 5 },
        { name: "Jema'a", id: 6 },
        { name: "Kachia", id: 7 },
        { name: "Kaduna North", id: 8 },
        { name: "Kaduna South", id: 9 },
        { name: "Kagarko", id: 10 },
        { name: "Kajuru", id: 11 },
        { name: "Kaura", id: 12 },
        { name: "Kauru", id: 13 },
        { name: "Kubau", id: 14 },
        { name: "Kudan", id: 15 },
        { name: "Lere", id: 16 },
        { name: "Makarfi", id: 17 },
        { name: "Sabon Gari", id: 18 },
        { name: "Sanga", id: 19 },
        { name: "Soba", id: 20 },
        { name: "Zangon Kataf", id: 21 },
        { name: "Zaria", id: 22 },
      ],
    },
  },
  {
    state: {
      name: "Kano State",
      id: 20,
      locals: [
        { name: "Albasu", id: 1 },
        { name: "Bagwai", id: 2 },
        { name: "Bebeji", id: 3 },
        { name: "Bichi", id: 4 },
        { name: "Bunkure", id: 5 },
        { name: "Dala", id: 6 },
        { name: "Dambatta", id: 7 },
        { name: "Dawakin Kudu", id: 8 },
        { name: "Dawakin Tofa", id: 9 },
        { name: "Doguwa", id: 10 },
        { name: "Fagge", id: 11 },
        { name: "Gabasawa", id: 12 },
        { name: "Garko", id: 13 },
        { name: "Garun Mallam", id: 14 },
        { name: "Gaya", id: 15 },
        { name: "Gezawa", id: 16 },
        { name: "Gwale", id: 17 },
        { name: "Gwarzo", id: 18 },
        { name: "Kabo", id: 19 },
        { name: "Kano Municipal", id: 20 },
        { name: "Karaye", id: 21 },
        { name: "Kibiya", id: 22 },
        { name: "Kiru", id: 23 },
        { name: "Kumbotso", id: 24 },
        { name: "Kunchi", id: 25 },
        { name: "Kura", id: 26 },
        { name: "Madobi", id: 27 },
        { name: "Makoda", id: 28 },
        { name: "Minjibir", id: 29 },
        { name: "Nasarawa", id: 30 },
        { name: "Rano", id: 31 },
        { name: "Rimin Gado", id: 32 },
        { name: "Rogo", id: 33 },
        { name: "Shanono", id: 34 },
        { name: "Sumaila", id: 35 },
        { name: "Takai", id: 36 },
        { name: "Tarauni", id: 37 },
        { name: "Tofa", id: 38 },
        { name: "Tsanyawa", id: 39 },
        { name: "Tudun Wada", id: 40 },
        { name: "Ungogo", id: 41 },
        { name: "Warawa", id: 42 },
        { name: "Wudil", id: 43 },
      ],
    },
  },
  {
    state: {
      name: "Katsina State",
      id: 21,
      locals: [
        { name: "Batagarawa", id: 1 },
        { name: "Batsari", id: 2 },
        { name: "Baure", id: 3 },
        { name: "Bindawa", id: 4 },
        { name: "Charanchi", id: 5 },
        { name: "Dandume", id: 6 },
        { name: "Danja", id: 7 },
        { name: "Dan Musa", id: 8 },
        { name: "Daura", id: 9 },
        { name: "Dutsi", id: 10 },
        { name: "Dutsin Ma", id: 11 },
        { name: "Faskari", id: 12 },
        { name: "Funtua", id: 13 },
        { name: "Ingawa", id: 14 },
        { name: "Jibia", id: 15 },
        { name: "Kafur", id: 16 },
        { name: "Kaita", id: 17 },
        { name: "Kankara", id: 18 },
        { name: "Kankia", id: 19 },
        { name: "Katsina", id: 20 },
        { name: "Kurfi", id: 21 },
        { name: "Kusada", id: 22 },
        { name: "Mai'Adua", id: 23 },
        { name: "Malumfashi", id: 24 },
        { name: "Mani", id: 25 },
        { name: "Mashi", id: 26 },
        { name: "Matazu", id: 27 },
        { name: "Musawa", id: 28 },
        { name: "Rimi", id: 29 },
        { name: "Sabuwa", id: 30 },
        { name: "Safana", id: 31 },
        { name: "Sandamu", id: 32 },
        { name: "Zango", id: 33 },
      ],
    },
  },
  {
    state: {
      name: "Kebbi State",
      id: 22,
      locals: [
        { name: "Arewa Dandi", id: 1 },
        { name: "Argungu", id: 2 },
        { name: "Augie", id: 3 },
        { name: "Bagudo", id: 4 },
        { name: "Birnin Kebbi", id: 5 },
        { name: "Bunza", id: 6 },
        { name: "Dandi", id: 7 },
        { name: "Fakai", id: 8 },
        { name: "Gwandu", id: 9 },
        { name: "Jega", id: 10 },
        { name: "Kalgo", id: 11 },
        { name: "Koko/Besse", id: 12 },
        { name: "Maiyama", id: 13 },
        { name: "Ngaski", id: 14 },
        { name: "Sakaba", id: 15 },
        { name: "Shanga", id: 16 },
        { name: "Suru", id: 17 },
        { name: "Wasagu/Danko", id: 18 },
        { name: "Yauri", id: 19 },
        { name: "Zuru", id: 20 },
      ],
    },
  },
  {
    state: {
      name: "Kogi State",
      id: 23,
      locals: [
        { name: "Ajaokuta", id: 1 },
        { name: "Ankpa", id: 2 },
        { name: "Bassa", id: 3 },
        { name: "Dekina", id: 4 },
        { name: "Ibaji", id: 5 },
        { name: "Idah", id: 6 },
        { name: "Igalamela Odolu", id: 7 },
        { name: "Ijumu", id: 8 },
        { name: "Kabba/Bunu", id: 9 },
        { name: "Kogi", id: 10 },
        { name: "Lokoja", id: 11 },
        { name: "Mopa Muro", id: 12 },
        { name: "Ofu", id: 13 },
        { name: "Ogori/Magongo", id: 14 },
        { name: "Okehi", id: 15 },
        { name: "Okene", id: 16 },
        { name: "Olamaboro", id: 17 },
        { name: "Omala", id: 18 },
        { name: "Yagba East", id: 19 },
        { name: "Yagba West", id: 20 },
      ],
    },
  },
  {
    state: {
      name: "Kwara State",
      id: 24,
      locals: [
        { name: "Baruten", id: 1 },
        { name: "Edu", id: 2 },
        { name: "Ekiti", id: 3 },
        { name: "Ifelodun", id: 4 },
        { name: "Ilorin East", id: 5 },
        { name: "Ilorin South", id: 6 },
        { name: "Ilorin West", id: 7 },
        { name: "Irepodun", id: 8 },
        { name: "Isin", id: 9 },
        { name: "Kaiama", id: 10 },
        { name: "Moro", id: 11 },
        { name: "Offa", id: 12 },
        { name: "Oke Ero", id: 13 },
        { name: "Oyun", id: 14 },
        { name: "Pategi", id: 15 },
      ],
    },
  },
  {
    state: {
      name: "Lagos State",
      id: 25,
      locals: [
        { name: "Ajeromi-Ifelodun", id: 1 },
        { name: "Alimosho", id: 2 },
        { name: "Amuwo-Odofin", id: 3 },
        { name: "Apapa", id: 4 },
        { name: "Badagry", id: 5 },
        { name: "Epe", id: 6 },
        { name: "Eti Osa", id: 7 },
        { name: "Ibeju-Lekki", id: 8 },
        { name: "Ifako-Ijaiye", id: 9 },
        { name: "Ikeja", id: 10 },
        { name: "Ikorodu", id: 11 },
        { name: "Kosofe", id: 12 },
        { name: "Lagos Island", id: 13 },
        { name: "Lagos Mainland", id: 14 },
        { name: "Mushin", id: 15 },
        { name: "Ojo", id: 16 },
        { name: "Oshodi-Isolo", id: 17 },
        { name: "Shomolu", id: 18 },
        { name: "Surulere", id: 19 },
      ],
    },
  },
  {
    state: {
      name: "Nasarawa State",
      id: 26,
      locals: [
        { name: "Awe", id: 1 },
        { name: "Doma", id: 2 },
        { name: "Karu", id: 3 },
        { name: "Keana", id: 4 },
        { name: "Keffi", id: 5 },
        { name: "Kokona", id: 6 },
        { name: "Lafia", id: 7 },
        { name: "Nasarawa", id: 8 },
        { name: "Nasarawa Egon", id: 9 },
        { name: "Obi", id: 10 },
        { name: "Toto", id: 11 },
        { name: "Wamba", id: 12 },
      ],
    },
  },
  {
    state: {
      name: "Niger State",
      id: 27,
      locals: [
        { name: "Agwara", id: 1 },
        { name: "Bida", id: 2 },
        { name: "Borgu", id: 3 },
        { name: "Bosso", id: 4 },
        { name: "Chanchaga", id: 5 },
        { name: "Edati", id: 6 },
        { name: "Gbako", id: 7 },
        { name: "Gurara", id: 8 },
        { name: "Katcha", id: 9 },
        { name: "Kontagora", id: 10 },
        { name: "Lapai", id: 11 },
        { name: "Lavun", id: 12 },
        { name: "Magama", id: 13 },
        { name: "Mariga", id: 14 },
        { name: "Mashegu", id: 15 },
        { name: "Mokwa", id: 16 },
        { name: "Moya", id: 17 },
        { name: "Paikoro", id: 18 },
        { name: "Rafi", id: 19 },
        { name: "Rijau", id: 20 },
        { name: "Shiroro", id: 21 },
        { name: "Suleja", id: 22 },
        { name: "Tafa", id: 23 },
        { name: "Wushishi", id: 24 },
      ],
    },
  },
  {
    state: {
      name: "Ogun State",
      id: 28,
      locals: [
        { name: "Abeokuta South", id: 1 },
        { name: "Ado-Odo/Ota", id: 2 },
        { name: "Egbado North", id: 3 },
        { name: "Egbado South", id: 4 },
        { name: "Ewekoro", id: 5 },
        { name: "Ifo", id: 6 },
        { name: "Ijebu East", id: 7 },
        { name: "Ijebu North", id: 8 },
        { name: "Ijebu North East", id: 9 },
        { name: "Ijebu Ode", id: 10 },
        { name: "Ikenne", id: 11 },
        { name: "Imeko Afon", id: 12 },
        { name: "Ipokia", id: 13 },
        { name: "Obafemi Owode", id: 14 },
        { name: "Odeda", id: 15 },
        { name: "Odogbolu", id: 16 },
        { name: "Ogun Waterside", id: 17 },
        { name: "Remo North", id: 18 },
        { name: "Shagamu", id: 19 },
      ],
    },
  },
  {
    state: {
      name: "Ondo State",
      id: 29,
      locals: [
        { name: "Akoko North-West", id: 1 },
        { name: "Akoko South-West", id: 2 },
        { name: "Akoko South-East", id: 3 },
        { name: "Akure North", id: 4 },
        { name: "Akure South", id: 5 },
        { name: "Ese Odo", id: 6 },
        { name: "Idanre", id: 7 },
        { name: "Ifedore", id: 8 },
        { name: "Ilaje", id: 9 },
        { name: "Ile Oluji/Okeigbo", id: 10 },
        { name: "Irele", id: 11 },
        { name: "Odigbo", id: 12 },
        { name: "Okitipupa", id: 13 },
        { name: "Ondo East", id: 14 },
        { name: "Ondo West", id: 15 },
        { name: "Ose", id: 16 },
        { name: "Owo", id: 17 },
      ],
    },
  },
  {
    state: {
      name: "Osun State",
      id: 30,
      locals: [
        { name: "Atakunmosa West", id: 1 },
        { name: "Aiyedaade", id: 2 },
        { name: "Aiyedire", id: 3 },
        { name: "Boluwaduro", id: 4 },
        { name: "Boripe", id: 5 },
        { name: "Ede North", id: 6 },
        { name: "Ede South", id: 7 },
        { name: "Ife Central", id: 8 },
        { name: "Ife East", id: 9 },
        { name: "Ife North", id: 10 },
        { name: "Ife South", id: 11 },
        { name: "Egbedore", id: 12 },
        { name: "Ejigbo", id: 13 },
        { name: "Ifedayo", id: 14 },
        { name: "Ifelodun", id: 15 },
        { name: "Ila", id: 16 },
        { name: "Ilesa East", id: 17 },
        { name: "Ilesa West", id: 18 },
        { name: "Irepodun", id: 19 },
        { name: "Irewole", id: 20 },
        { name: "Isokan", id: 21 },
        { name: "Iwo", id: 22 },
        { name: "Obokun", id: 23 },
        { name: "Odo Otin", id: 24 },
        { name: "Ola Oluwa", id: 25 },
        { name: "Olorunda", id: 26 },
        { name: "Oriade", id: 27 },
        { name: "Orolu", id: 28 },
        { name: "Osogbo", id: 29 },
      ],
    },
  },
  {
    state: {
      name: "Oyo State",
      id: 31,
      locals: [
        { name: "Akinyele", id: 1 },
        { name: "Atiba", id: 2 },
        { name: "Atisbo", id: 3 },
        { name: "Egbeda", id: 4 },
        { name: "Ibadan North", id: 5 },
        { name: "Ibadan North-East", id: 6 },
        { name: "Ibadan North-West", id: 7 },
        { name: "Ibadan South-East", id: 8 },
        { name: "Ibadan South-West", id: 9 },
        { name: "Ibarapa Central", id: 10 },
        { name: "Ibarapa East", id: 11 },
        { name: "Ibarapa North", id: 12 },
        { name: "Ido", id: 13 },
        { name: "Irepo", id: 14 },
        { name: "Iseyin", id: 15 },
        { name: "Itesiwaju", id: 16 },
        { name: "Iwajowa", id: 17 },
        { name: "Kajola", id: 18 },
        { name: "Lagelu", id: 19 },
        { name: "Ogbomosho North", id: 20 },
        { name: "Ogbomosho South", id: 21 },
        { name: "Ogo Oluwa", id: 22 },
        { name: "Olorunsogo", id: 23 },
        { name: "Oluyole", id: 24 },
        { name: "Ona Ara", id: 25 },
        { name: "Orelope", id: 26 },
        { name: "Ori Ire", id: 27 },
        { name: "Oyo", id: 28 },
        { name: "Oyo East", id: 29 },
        { name: "Saki East", id: 30 },
        { name: "Saki West", id: 31 },
        { name: "Surulere", id: 32 },
      ],
    },
  },
  {
    state: {
      name: "Plateau State",
      id: 32,
      locals: [
        { name: "Barkin Ladi", id: 1 },
        { name: "Bassa", id: 2 },
        { name: "Jos East", id: 3 },
        { name: "Jos North", id: 4 },
        { name: "Jos South", id: 5 },
        { name: "Kanam", id: 6 },
        { name: "Kanke", id: 7 },
        { name: "Langtang South", id: 8 },
        { name: "Langtang North", id: 9 },
        { name: "Mangu", id: 10 },
        { name: "Mikang", id: 11 },
        { name: "Pankshin", id: 12 },
        { name: "Qua'an Pan", id: 13 },
        { name: "Riyom", id: 14 },
        { name: "Shendam", id: 15 },
        { name: "Wase", id: 16 },
      ],
    },
  },
  {
    state: {
      name: "Rivers State",
      id: 33,
      locals: [
        { name: "Ahoada East", id: 1 },
        { name: "Ahoada West", id: 2 },
        { name: "Akuku-Toru", id: 3 },
        { name: "Andoni", id: 4 },
        { name: "Asari-Toru", id: 5 },
        { name: "Bonny", id: 6 },
        { name: "Degema", id: 7 },
        { name: "Eleme", id: 8 },
        { name: "Emuoha", id: 9 },
        { name: "Etche", id: 10 },
        { name: "Gokana", id: 11 },
        { name: "Ikwerre", id: 12 },
        { name: "Khana", id: 13 },
        { name: "Obio/Akpor", id: 14 },
        { name: "Ogba/Egbema/Ndoni", id: 15 },
        { name: "Ogu/Bolo", id: 16 },
        { name: "Okrika", id: 17 },
        { name: "Omuma", id: 18 },
        { name: "Opobo/Nkoro", id: 19 },
        { name: "Oyigbo", id: 20 },
        { name: "Port Harcourt", id: 21 },
        { name: "Tai", id: 22 },
      ],
    },
  },
  {
    state: {
      name: "Sokoto State",
      id: 34,
      locals: [
        { name: "Bodinga", id: 1 },
        { name: "Dange Shuni", id: 2 },
        { name: "Gada", id: 3 },
        { name: "Goronyo", id: 4 },
        { name: "Gudu", id: 5 },
        { name: "Gwadabawa", id: 6 },
        { name: "Illela", id: 7 },
        { name: "Isa", id: 8 },
        { name: "Kebbe", id: 9 },
        { name: "Kware", id: 10 },
        { name: "Rabah", id: 11 },
        { name: "Sabon Birni", id: 12 },
        { name: "Shagari", id: 13 },
        { name: "Silame", id: 14 },
        { name: "Sokoto North", id: 15 },
        { name: "Sokoto South", id: 16 },
        { name: "Tambuwal", id: 17 },
        { name: "Tangaza", id: 18 },
        { name: "Tureta", id: 19 },
        { name: "Wamako", id: 20 },
        { name: "Wurno", id: 21 },
        { name: "Yabo", id: 22 },
      ],
    },
  },
  {
    state: {
      name: "Taraba State",
      id: 35,
      locals: [
        { name: "Bali", id: 1 },
        { name: "Donga", id: 2 },
        { name: "Gashaka", id: 3 },
        { name: "Gassol", id: 4 },
        { name: "Ibi", id: 5 },
        { name: "Jalingo", id: 6 },
        { name: "Karim Lamido", id: 7 },
        { name: "Kumi", id: 8 },
        { name: "Lau", id: 9 },
        { name: "Sardauna", id: 10 },
        { name: "Takum", id: 11 },
        { name: "Ussa", id: 12 },
        { name: "Wukari", id: 13 },
        { name: "Yorro", id: 14 },
        { name: "Zing", id: 15 },
      ],
    },
  },
  {
    state: {
      name: "Yobe State",
      id: 36,
      locals: [
        { name: "Bursari", id: 1 },
        { name: "Damaturu", id: 2 },
        { name: "Fika", id: 3 },
        { name: "Fune", id: 4 },
        { name: "Geidam", id: 5 },
        { name: "Gujba", id: 6 },
        { name: "Gulani", id: 7 },
        { name: "Jakusko", id: 8 },
        { name: "Karasuwa", id: 9 },
        { name: "Machina", id: 10 },
        { name: "Nangere", id: 11 },
        { name: "Nguru", id: 12 },
        { name: "Potiskum", id: 13 },
        { name: "Tarmuwa", id: 14 },
        { name: "Yunusari", id: 15 },
        { name: "Yusufari", id: 16 },
      ],
    },
  },
  {
    state: {
      name: "Zamfara State",
      id: 37,
      locals: [
        { name: "Bakura", id: 1 },
        { name: "Birnin Magaji/Kiyaw", id: 2 },
        { name: "Bukkuyum", id: 3 },
        { name: "Bungudu", id: 4 },
        { name: "Gummi", id: 5 },
        { name: "Gusau", id: 6 },
        { name: "Kaura Namoda", id: 7 },
        { name: "Maradun", id: 8 },
        { name: "Maru", id: 9 },
        { name: "Shinkafi", id: 10 },
        { name: "Talata Mafara", id: 11 },
        { name: "Chafe", id: 12 },
        { name: "Zurmi", id: 13 },
      ],
    },
  },
];

export const states_data = [
  {
    state: "Abia State",
    cities: [
      "Aba North",
      "Aba South",
      "Umuahia",
      "Arochukwu",
      "Bende",
      "Ikwuano",
      "Isiala Ngwa",
      "Isuikwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma Ngwa",
      "Ugwunagbo",
      "Ukwa",
      "Umu Nneochi",
    ],
  },
  {
    state: "Abuja",
    cities: [
      "Gwarinpa",
      "Kubwa",
      "Wuse",
      "Wuse 2",
      "Abaji",
      "Apo District",
      "Asokoro",
      "Bwari",
      "Dakibiyu",
      "Dakwo District",
      "Dei-Dei",
      "Duboyi",
      "Durumi",
      "Dutse-Alhaji",
      "Gaduwa",
      "Galadimawa",
      "Garki 1",
      "Garki 2",
      "Gudu",
      "Guzape District",
      "Gwagwa",
      "Gwagwalada",
      "Idu Industrial",
      "Jabi",
      "Jahi",
      "Jikwoyi",
      "Jiwa",
      "Kabusa",
      "Kado",
      "Karmo",
      "Karshi",
      "Karu",
      "Katampe",
      "Kaura",
      "Kpeyegyi",
    ],
  },
  {
    state: "Adamawa State",
    cities: [
      "Yola North",
      "Yola South",
      "Demsa",
      "Fufore",
      "Ganye",
      "Girei",
      "Gombi",
      "Guyuk",
      "Hong",
      "Jada",
      "Lamurde",
      "Madagali",
      "Maiha",
      "Mayo-Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
    ],
  },
  {
    state: "Akwa Ibom State",
    cities: [
      "Abak",
      "Eket",
      "Ikot Ekpene",
      "Oron",
      "Uyo",
      "Eastern Obolo",
      "Esit-Eket",
      "Essien Udim",
      "Etim-Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo Asutan",
      "Ibiono Ibom",
      "Ika",
      "Ikono",
      "Ikot Abasi",
      "Ini",
      "Itu",
      "Mbo",
      "Mkpat Enin",
      "Nsit Atai",
      "Nsit Ibom",
      "Nsit Ubium",
    ],
  },
  {
    state: "Anambra State",
    cities: [
      "Awka",
      "Idemili",
      "Nnewi",
      "Onitsha",
      "Aghamelu",
      "Aguata",
      "Anambra East",
      "Anambra West",
      "Anaocha",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Ihiala",
      "Njikoka",
      "Ogbaru",
      "Orumba",
      "Oyi",
    ],
  },
  {
    state: "Bauchi State",
    cities: [
      "Yenagoa",
      "Brass",
      "Ekeremor",
      "Kolokuma/Opokuma",
      "Nembe",
      "Ogbia",
      "Sagbama",
      "Southern Ijaw",
    ],
  },
  {
    state: "Bayelsa State",
    cities: [
      "Yenagoa",
      "Brass",
      "Ekeremor",
      "Kolokuma/Opokuma",
      "Nembe",
      "Ogbia",
      "Sagbama",
      "Southern Ijaw",
    ],
  },
  {
    state: "Benue State",
    cities: [
      "Gboko",
      "Katsina-Ala",
      "Makurdi",
      "Otukpo",
      "Ado",
      "Agatu",
      "Apa",
      "Buruku",
      "Guma",
      "Gwer",
      "Konshisha",
      "Kwande",
      "Logo",
      "Obi",
      "Ogbadibo",
      "Ohimini",
      "Oju",
      "Okpokwu",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya",
    ],
  },
  {
    state: "Borno State",
    cities: [
      "Maiduguri",
      "Abadam",
      "Askira/Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Gubio",
      "Guzamala",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kala/Balge",
      "Konduga",
      "Kukawa",
      "Kwaya Kusar",
      "Mafa",
      "Magumeri",
      "Marte",
      "Mobbar",
    ],
  },
  {
    state: "Cross River State",
    cities: [
      "Calabar",
      "Ikom",
      "Ogoja",
      "Abi",
      "Akamkpa",
      "Akpabuyo",
      "Bakassi",
      "Bekwara",
      "Biase",
      "Boki",
      "Etung",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Yakuur",
      "Yala",
    ],
  },
  {
    state: "Delta State",
    cities: [
      "Oshimili South",
      "Sapele",
      "Ugheli",
      "Uvwie",
      "Warri",
      "Aniocha North",
      "Aniocha South",
      "Bomadi",
      "Burutu",
      "Ethiope East",
      "Ethiope West",
      "Ika North East",
      "Ika South",
      "Isoko",
      "Ndokwa East",
      "Ndokwa West",
      "Okpe",
      "Oshimili North",
      "Patani",
      "Udu",
      "Ukwuani",
    ],
  },
  {
    state: "Ebonyi State",
    cities: [
      "Abakaliki",
      "Afikpo North",
      "Afikpo South",
      "Ebonyi",
      "Ezza",
      "Ikwo",
      "Ishielu",
      "Ivo",
      "Izzi",
      "Ohaozara",
      "Ohaukwu",
    ],
  },
  {
    state: "Edo State",
    cities: [
      "Benin City",
      "Egor",
      "Ekpoma",
      "Ikpoba-Okha",
      "Okada",
      "Akoko-Edo",
      "Auchi",
      "Esan North East",
      "Fugar",
      "Igueben",
      "Irrua",
      "Orhionmwon",
      "Ovia South",
      "Owan",
      "Ubiaja",
      "Uhunmwonde",
    ],
  },
  {
    state: "Ekiti State",
    cities: [
      "Ado Ekiti",
      "Ido-Osi",
      "Ikere",
      "Ikole",
      "Ilawe",
      "Aiyekire (Gbonyin)",
      "Aramoko",
      "Efon",
      "Emure",
      "Ijero",
      "Ilejemeje",
      "Irepodun/Ifelodun",
      "Ise/Orun",
      "Moba",
      "Omuo",
      "Oye",
    ],
  },
  {
    state: "Enugu State",
    cities: [
      "Enugu",
      "Nkanu West",
      "Nsukka",
      "Udi",
      "Aninri",
      "Awgu",
      "Ezeagu",
      "Igbo Eze South",
      "Igbo-Etiti",
      "Igbo-Eze North",
      "Isi-Uzo",
      "Nkanu East",
      "Oji-River",
      "Udenu",
      "Uzo-Uwani",
    ],
  },
  {
    state: "Gombe State",
    cities: [
      "Gombe LGA",
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shomgom",
      "Yamaltu/Deba",
    ],
  },
  {
    state: "Imo State",
    cities: [
      "Ikeduru",
      "Mbaitoli",
      "Okigwe",
      "Orlu",
      "Owerri",
      "Aboh-Mbaise",
      "Ahiazu-Mbaise",
      "Ehime-Mbano",
      "Ezinihitte",
      "Ezinihitte Mbaise",
      "Ideato North",
      "Ideato South",
      "Ihitte/Uboma",
      "Isiala Mbano",
      "Isu",
      "Ngor-Okpala",
      "Njaba",
      "Nkwerre",
      "Nwangele",
      "Obowo",
      "Oguta",
      "Ohaji/Egbema",
      "Onuimo",
    ],
  },
  {
    state: "Jigawa State",
    cities: [
      "Dutse-Jigawa",
      "Garki",
      "Auyo",
      "Babura",
      "Biriniwa",
      "Buji",
      "Gagarawa",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kaugama",
      "Kazaure",
      "Kiri Kasamma",
      "Kiyawa",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Ringim",
      "Roni",
    ],
  },
  {
    state: "Kaduna State",
    cities: [
      "Chikun",
      "Igabi",
      "Kaduna / Kaduna State",
      "Zaria",
      "Birnin-Gwari",
      "Giwa",
      "Ikara",
      "Jaba",
      "Jema'a",
      "Kachia",
      "Kagarko",
      "Kajuru",
      "Kaura-Kaduna",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sanga",
      "Soba",
      "Zango-Kataf",
    ],
  },
  {
    state: "Kano State",
    cities: [
      "Fagge",
      "Kano Municipal",
      "Nasarawa-Kano",
      "Tarauni",
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Dambatta",
      "Dawakin Kudu",
      "Dawakin Tofa",
      "Doguwa",
      "Gabasawa",
      "Garko",
      "Garum Mallam",
      "Garun Mallam",
      "Gaya",
      "Gezawa",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
    ],
  },
  {
    state: "Katsina State",
    cities: [
      "Danja",
      "Daura",
      "Katsina",
      "Zango",
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Dan Musa",
      "Dandume",
      "Dutsi",
      "Dutsin-Ma",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Kurfi",
    ],
  },
  {
    state: "Kebbi State",
    cities: [
      "Birnin Kebbi",
      "Jega",
      "Zuru",
      "Aleiro",
      "Arewa-Dandi",
      "Argungu",
      "Augie",
      "Bagudo",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Kalgo",
      "Koko/Besse",
      "Maiyama",
      "Ngaski",
      "Sakaba",
      "Shanga",
      "Suru",
      "Wasagu/Danko",
      "Yauri",
    ],
  },
  {
    state: "Kogi State",
    cities: [
      "Lokoja",
      "Okene",
      "Adavi",
      "Ajaokuta",
      "Ankpa",
      "Bassa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igala Mela",
      "Igalamela-Odolu",
      "Ijumu",
      "Kabba/Bunu",
      "Kogi LGA",
      "Koton Karfe",
      "Mopa-Muro",
      "Ofu",
      "Ogori/Magongo",
      "Okehi",
      "Olamaboro",
      "Omala",
      "Yagba East",
      "Yagba West",
    ],
  },
  {
    state: "Kwara State",
    cities: [
      "Ilorin East",
      "Ilorin South",
      "Ilorin West",
      "Asa",
      "Baruten",
      "Edu",
      "Ekiti-Kwara",
      "Ifelodun-Kwara",
      "Irepodun-Kwara",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke-Ero",
      "Oyun",
      "Pategi",
    ],
  },
  {
    state: "Lagos State",
    cities: [
      "Ajah",
      "Alimosho",
      "Ikeja",
      "Ojo",
      "Surulere",
      "Abule Egba",
      "Agbara-Igbesan",
      "Agboyi/Ketu",
      "Agege",
      "Amuwo-Odofin",
      "Apapa",
      "Badagry",
      "Egbe/Idimu",
      "Ejigbo",
      "Eko Atlantic",
      "Epe",
      "Gbagada",
      "Ibeju",
      "Ifako-Ijaiye",
      "Ikorodu",
      "Ikotun/Igando",
      "Ikoyi",
      "Ilashe",
      "Ilupeju",
      "Ipaja",
      "Isolo",
    ],
  },
  {
    state: "Nasarawa State",
    cities: [
      "Karu-Nasarawa",
      "Keffi",
      "Lafia",
      "Akwanga",
      "Awe",
      "Doma",
      "Keana",
      "Kokona",
      "Nasarawa",
      "Nasarawa-Eggon",
      "Obi-Nasarawa",
      "Toto",
      "Wamba",
    ],
  },
  {
    state: "Niger State",
    cities: [
      "Bida",
      "Bosso",
      "Chanchaga",
      "Minna",
      "Suleja",
      "Agaie",
      "Agwara",
      "Borgu",
      "Edati",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Magama",
      "Mariga",
      "Mashegu",
      "Mokwa",
      "Muya",
      "Paikoro",
      "Rafi",
      "Rijau",
    ],
  },
  {
    state: "Ogun State",
    cities: [
      "Abeokuta South",
      "Ado-Odo/Ota",
      "Ijebu Ode",
      "Obafemi-Owode",
      "Sagamu",
      "Abeokuta North",
      "Ayetoro",
      "Ewekoro",
      "Ifo",
      "Ijebu",
      "Ikenne",
      "Ilaro",
      "Imeko Afon",
      "Ipokia",
      "Iseri",
      "Odeda",
      "Odogbolu",
      "Ogun Waterside",
      "Pakuro",
      "Remo North",
    ],
  },
  {
    state: "Ondo State",
    cities: [
      "Akure",
      "Iju/Itaogbolu",
      "Okitipupa",
      "Ondo",
      "Owo",
      "Akungba",
      "Ese-Odo",
      "Idanre",
      "Ifedore",
      "Ikare Akoko",
      "Ilaje",
      "Ile-Oluji-Okeigbo",
      "Irele",
      "Isua",
      "Odigbo",
      "Oka",
      "Okeagbe",
      "Okeigbo",
      "Ose",
    ],
  },
  {
    state: "Osun State",
    cities: [
      "Ede",
      "Ife",
      "Ilesa",
      "Olorunda-Osun",
      "Osogbo",
      "Aiyedade",
      "Aiyedire",
      "Atakumosa East",
      "Atakumosa West",
      "Boluwaduro",
      "Boripe",
      "Egbedore",
      "Ifedayo",
      "Ifelodun-Osun",
      "Ikirun",
      "Ila",
      "Irepodun-Osun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Ola-Oluwa",
      "Oriade",
    ],
  },
  {
    state: "Oyo State",
    cities: [
      "Akinyele",
      "Egbeda",
      "Ibadan",
      "Ido",
      "Oluyole",
      "Afijio",
      "Atiba",
      "Atisbo",
      "Ayete",
      "Eruwa",
      "Igbo Ora",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogbomosho North",
      "Ogbomosho South",
      "Ogo Oluwa",
      "Olorunsogo",
      "Ona-Ara",
      "Orelope",
    ],
  },
  {
    state: "Plateau State",
    cities: [
      "Jos",
      "Barkin Ladi",
      "Bassa-Plateau",
      "Bokkos",
      "Kanam",
      "Kanke",
      "Langtang North",
      "Langtang South",
      "Mangu",
      "Mikang",
      "Pankshin",
      "Quaan Pan",
      "Riyom",
      "Shendam",
      "Wase",
    ],
  },
  {
    state: "Rivers State",
    cities: [
      "Eleme",
      "Ikwerre",
      "Obio-Akpor",
      "Oyigbo",
      "Port-Harcourt",
      "Abua/Odual",
      "Ahoada",
      "Akuku Toru",
      "Andoni",
      "Asari-Toru",
      "Bonny",
      "Degema",
      "Emohua",
      "Etche",
      "Gokana",
      "Khana",
      "Ogba/Egbema/Ndoni",
      "Ogu/Bolo",
      "Okrika",
      "Omuma",
      "Tai",
    ],
  },
  {
    state: "Sokoto State",
    cities: [
      "Illela",
      "Sokoto North",
      "Sokoto South",
      "Binji",
      "Bodinga",
      "Dange-Shuni",
      "Gada",
      "Goronyo",
      "Gudu LGA",
      "Gwadabawa",
      "Isa",
      "Kebbe",
      "Kware",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
    ],
  },
  {
    state: "Taraba State",
    cities: [
      "Jalingo",
      "Takum",
      "Wukari",
      "Ardo-Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Karim-Lamido",
      "Kurmi",
      "Lau",
      "Sardauna",
      "Ussa",
      "Yorro",
      "Zing",
    ],
  },
  {
    state: "Yobe State",
    cities: [
      "Damaturu",
      "Potiskum",
      "Bade",
      "Bursari",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Tarmua",
      "Yunusari",
      "Yusufari",
    ],
  },
  {
    state: "Zamfara State",
    cities: [
      "Gusau",
      "Anka",
      "Bakura",
      "Birnin Magaji",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Kaura Namoda",
      "Maradun",
      "Maru",
      "Shinkafi",
      "Talata Mafara",
      "Tsafe",
      "Zurmi",
    ],
  },
];

export const loanSteps: string[] = [
  "Download Splitam either on Play Store or App Store and sign up easily. You can also sign up on the web app!",
  "Submit a valid identification document",
  "Apply for a loan on your dashboard and fill out the necessary fields. If eligible, accept your loan offer and have your loan amount credited within 3-5 minutes",
  "Our system is algorithm-driven and this drives our loan decisioning process",
];
export const savingsSteps: string[] = [
  "Save your funds towards rainy days and earn cool interests with Splitam",
  "All you need to do is submit a valid Means of identification and a documentary Evidence of Address/Address Verification Form",
  "Enjoy unlimited access to deposit and withdrawal!",
];

export interface FAQ {
  question: string;
  answer: string;
}

export const faqs: FAQ[] = [
  {
    question: "What is Splitam?",
    answer:
      "Splitam is an online platform that lets you team up with people around you to split costs on products, transportation, accommodation, and more",
  },
  {
    question: "How do I get started?",
    answer:
      "Our app is easily accessible on Google Store and App Store for download and you can get started in just a few minutes and most importantly, it is completely free.",
  },
  {
    question: "Is Splitam registered?",
    answer: "Yes, Splitam is a product of Splitam Technologies Limited (RC 7039874)",
  },
  {
    question: "How do I split the cost of an item?",
    answer:
      "You can do this by creating a split group on the app, and then people interested in splitting the cost of the item with you will join the group. Launch the app and click on the split button at the bottom center of the screen, the rest is ABC.",
  },
  {
    question: "What is a split group?",
    answer:
      "This is a normal group where people with similar interests in splitting the cost of an item, come together to share cost. You can create a new split group or join an existing split group on the app.",
  },
  {
    question: "Do i need to pay to join a split group?",
    answer:
      "There are no fees attached to joining a split group it`s completely free. However, some groups require members to make an initial deposit to the group wallet before they are allowed to join the group.",
  },
  {
    question: "Is my money secure in the group wallet?",
    answer:
      "Absolutely, before funds can be disbursed from a group wallet, every member of the group needs to give their approval.",
  },
  {
    question: "What happens to my money when I get kicked out of a group?",
    answer:
      "All your payment contributions to the group wallet will automatically be returned to you, so you have full control of your money.",
  },
  {
    question: "How do I pay to the group wallet?",
    answer:
      "You can easily contribute to a group by clicking the top-up button in your split group. Please ensure your group wallet is funded",
  },
  {
    question: "How do I exit a group?",
    answer:
      "Exiting a group us easy, just click on the button at the to right corner in your group.",
  },
  {
    question: "What happens to my money when I want to leave a group?",
    answer: "All your payment contrubitons get refunded to your wallet automatically.",
  },
  {
    question: "Can I send money to people in my spit group?",
    answer:
      "No, this is not advisable, all payments and contributions should be made using the group wallet.",
  },
  {
    question: "How many people can be in a split group?",
    answer: "A group can have up to 10 members.",
  },
  {
    question: "Can a group just have 2 persons?",
    answer: "Yes, 2 persons can form a group",
  },

  {
    question: "Can we use cash instead of the group wallet?",
    answer: "Yes, you can ignore group wallet and contribute cash instead",
  },

  {
    question: "How can the money in our split group be utilized?",
    answer:
      "Any member of the group and initiate a fund transfer from the group wallet, but the fund transfer has to be approved by every member of the group.",
  },

  {
    question: "How do i approve a fund transfer in my split group?",
    answer: "You will get a notification of the fund transfer and approve it if you wish.",
  },
];

export const recentList = [
  {
    country: "nigeria",
    costTitle: "Transport Cost",
    cashPayment: true,
    title: "FMC at Asaba with a rented car",
    userImage:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/f95d9a30-7e3d-11ee-8734-cbd3f5ce79d9?alt=media&token=ba6040f1-2dfe-4c72-81f2-f0e5aae01dca",
    costType: 2,
    timeCreated: 1699451857678,
    state: "delta state",
    inReview: false,
    fullTitle: "Co-Ride to FMC at Asaba with a rented car",
    itemCost1: 0,
    visibility: 0,
    itemCost: 0,
    splitCount: 2,
    privateGroup: false,
    userName: "Benson Nwosu",
    userId: "1ezb13oBK0QqtesadTUkculmVbu2",
    relevance: 0,
    mediaList: [],
    openJoin: false,
    categoryIcon:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/1a2a6360-49c3-11ee-9221-f58405cc093b?alt=media&token=7bdf248e-9eeb-4422-9855-00936f10ab1b",
    parties: [],
    setup: true,
    region: "ndokwa east",
    categoryId: "417cb2a0-33c1-11ee-8260-3da8291766a7",
    status: 1,
    createdAt: {
      _seconds: 1699451857,
      _nanoseconds: 755000000,
    },
    createdTime: {
      _seconds: 1699451857,
      _nanoseconds: 755000000,
    },
    reviewStart: {
      _seconds: 1699451857,
      _nanoseconds: 755000000,
    },
    updatedAt: {
      _seconds: 1699451857,
      _nanoseconds: 755000000,
    },
    id: "SQeKnRrunGxY44kbC59b",
    declinedRequest: [],
    joinRequest: [],
    inviteList: [],
    partiesCount: 1,
  },
  {
    country: "nigeria",
    costTitle: "Rent Cost",
    cashPayment: true,
    title: "an apartment in Delta",
    userImage:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/f95d9a30-7e3d-11ee-8734-cbd3f5ce79d9?alt=media&token=ba6040f1-2dfe-4c72-81f2-f0e5aae01dca",
    costType: 0,
    timeCreated: 1699451828231,
    state: "delta state",
    inReview: false,
    fullTitle: "Co-Rent an apartment in Delta",
    itemCost1: 0,
    visibility: 0,
    itemCost: 500000,
    splitCount: 2,
    privateGroup: false,
    userName: "Benson Nwosu",
    userId: "1ezb13oBK0QqtesadTUkculmVbu2",
    relevance: 0,
    mediaList: [],
    openJoin: false,
    categoryIcon:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/f9606030-49c2-11ee-9221-f58405cc093b?alt=media&token=bc3628ce-854f-4b22-8467-14438a390f56",
    parties: [],
    setup: true,
    region: "ndokwa east",
    categoryId: "41fd70d0-33c0-11ee-8260-3da8291766a7",
    status: 1,
    createdAt: {
      _seconds: 1699451828,
      _nanoseconds: 253000000,
    },
    createdTime: {
      _seconds: 1699451828,
      _nanoseconds: 253000000,
    },
    reviewStart: {
      _seconds: 1699451828,
      _nanoseconds: 253000000,
    },
    updatedAt: {
      _seconds: 1699451828,
      _nanoseconds: 253000000,
    },
    id: "2ZpEaDDGXPfxRkxgXWN2",
    declinedRequest: [],
    joinRequest: [],
    inviteList: [],
    partiesCount: 1,
  },
  {
    country: "nigeria",
    costTitle: "Purchase Cost",
    cashPayment: true,
    title: "a carton of butter",
    userImage:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/f95d9a30-7e3d-11ee-8734-cbd3f5ce79d9?alt=media&token=ba6040f1-2dfe-4c72-81f2-f0e5aae01dca",
    costType: 0,
    timeCreated: 1699451776778,
    state: "delta state",
    inReview: false,
    fullTitle: "Co-Buy a carton of butter",
    itemCost1: 0,
    visibility: 0,
    itemCost: 32000,
    splitCount: 2,
    privateGroup: false,
    userName: "Benson Nwosu",
    userId: "1ezb13oBK0QqtesadTUkculmVbu2",
    relevance: 0,
    mediaList: [],
    openJoin: false,
    categoryIcon:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/c8267270-49c2-11ee-9221-f58405cc093b?alt=media&token=751d32b7-bc1c-49a8-9c4e-4a753608e39c",
    parties: [],
    setup: true,
    region: "ndokwa east",
    categoryId: "27e89a40-33b0-11ee-9ee7-bdbd733e67db",
    status: 1,
    createdAt: {
      _seconds: 1699451776,
      _nanoseconds: 861000000,
    },
    createdTime: {
      _seconds: 1699451776,
      _nanoseconds: 861000000,
    },
    reviewStart: {
      _seconds: 1699451776,
      _nanoseconds: 861000000,
    },
    updatedAt: {
      _seconds: 1699451776,
      _nanoseconds: 861000000,
    },
    id: "IHYAvX4ZxOvGgAqwUKLK",
    declinedRequest: [],
    joinRequest: [],
    inviteList: [],
    partiesCount: 1,
  },
  {
    country: "nigeria",
    costTitle: "Transport Cost",
    cashPayment: true,
    title: "ShopRite at ikeja with Uber",
    userImage:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/6968e280-6acf-11ee-9614-e124171b99bc?alt=media&token=6636ff1c-a905-444d-86aa-59e05089f569",
    costType: 0,
    timeCreated: 1699357269895,
    state: "lagos state",
    inReview: false,
    fullTitle: "Co-Ride to ShopRite at ikeja with Uber",
    itemCost1: 0,
    visibility: 0,
    itemCost: 8000,
    splitCount: 2,
    privateGroup: false,
    userName: "Rebecca Sampson",
    userId: "pI4aodY0EJYFBadR5LyueoQNat43",
    relevance: 0,
    mediaList: [],
    openJoin: true,
    categoryIcon:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/1a2a6360-49c3-11ee-9221-f58405cc093b?alt=media&token=7bdf248e-9eeb-4422-9855-00936f10ab1b",
    parties: [],
    setup: true,
    region: "ikeja",
    categoryId: "417cb2a0-33c1-11ee-8260-3da8291766a7",
    status: 1,
    createdAt: {
      _seconds: 1699357269,
      _nanoseconds: 983000000,
    },
    createdTime: {
      _seconds: 1699357269,
      _nanoseconds: 983000000,
    },
    reviewStart: {
      _seconds: 1699357269,
      _nanoseconds: 983000000,
    },
    updatedAt: {
      _seconds: 1699357269,
      _nanoseconds: 983000000,
    },
    id: "erxDgHhLtGGfHeb3ciq4",
    declinedRequest: [],
    joinRequest: [],
    inviteList: [],
    partiesCount: 1,
  },
  {
    country: "nigeria",
    costTitle: "Transport Cost",
    cashPayment: true,
    title: "ShopRite at ikeja with Uber",
    userImage:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/2c44af10-6a2f-11ee-96e8-7941367aa649?alt=media&token=840719eb-cfb4-4e65-a196-3e4f76a5fe97",
    costType: 2,
    timeCreated: 1699278087952,
    state: "ondo state",
    inReview: false,
    fullTitle: "Co-Ride to ShopRite at ikeja with Uber",
    itemCost1: 0,
    visibility: 0,
    itemCost: 0,
    splitCount: 2,
    privateGroup: false,
    userName: "Paul Adebayo",
    userId: "DXhnoPcO0LfmejgG5Be8kvugl9Y2",
    relevance: 0,
    mediaList: [],
    openJoin: true,
    categoryIcon:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/1a2a6360-49c3-11ee-9221-f58405cc093b?alt=media&token=7bdf248e-9eeb-4422-9855-00936f10ab1b",
    parties: [],
    setup: true,
    region: "akure",
    categoryId: "417cb2a0-33c1-11ee-8260-3da8291766a7",
    status: 1,
    createdAt: {
      _seconds: 1699278088,
      _nanoseconds: 75000000,
    },
    createdTime: {
      _seconds: 1699278088,
      _nanoseconds: 75000000,
    },
    reviewStart: {
      _seconds: 1699278088,
      _nanoseconds: 75000000,
    },
    updatedAt: {
      _seconds: 1699278088,
      _nanoseconds: 75000000,
    },
    id: "JvAYWvKpVtSh2r1eT9Lz",
    declinedRequest: [],
    joinRequest: [],
    inviteList: [],
    partiesCount: 1,
  },
  {
    country: "nigeria",
    costTitle: "Purchase Cost",
    cashPayment: false,
    title: "a carton of butter",
    userImage:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/2c44af10-6a2f-11ee-96e8-7941367aa649?alt=media&token=840719eb-cfb4-4e65-a196-3e4f76a5fe97",
    costType: 0,
    timeCreated: 1699277673721,
    state: "ondo state",
    inReview: false,
    fullTitle: "Co-Buy a carton of butter",
    itemCost1: 0,
    visibility: 0,
    itemCost: 150,
    splitCount: 2,
    privateGroup: false,
    userName: "Paul Adebayo",
    userId: "DXhnoPcO0LfmejgG5Be8kvugl9Y2",
    relevance: 0,
    mediaList: [
      {
        filePath:
          "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/260b5c20-7ca9-11ee-8841-6723908b6d40?alt=media&token=d2ac018f-f9d5-49b3-8d65-fd5620d1c239",
        isGif: false,
        width: 450,
        isVideo: false,
        id: "1000000181",
        thumbPath: "/data/user/0/com.splitam/cacherice_main.png",
        type: "image",
        fileLength: null,
        height: 150,
      },
    ],
    openJoin: false,
    categoryIcon:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/c8267270-49c2-11ee-9221-f58405cc093b?alt=media&token=751d32b7-bc1c-49a8-9c4e-4a753608e39c",
    setup: true,
    region: "akure",
    categoryId: "27e89a40-33b0-11ee-9ee7-bdbd733e67db",
    createdAt: {
      _seconds: 1699277673,
      _nanoseconds: 878000000,
    },
    createdTime: {
      _seconds: 1699277673,
      _nanoseconds: 878000000,
    },
    updatedAt: {
      _seconds: 1699277673,
      _nanoseconds: 878000000,
    },
    id: "xe4oZmgELnR6F2n9Dhxe",
    joinRequest: [],
    parties: [],
    status: 1,
    reviewStart: {
      _seconds: 1699277696,
      _nanoseconds: 81000000,
    },
    declinedRequest: [],
    inviteList: [],
    partiesCount: 1,
  },
  {
    country: "nigeria",
    costTitle: "Purchase Cost",
    cashPayment: true,
    title: "a bag of rice",
    userImage:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/2c44af10-6a2f-11ee-96e8-7941367aa649?alt=media&token=840719eb-cfb4-4e65-a196-3e4f76a5fe97",
    costType: 0,
    timeCreated: 1699247122309,
    state: "ondo state",
    inReview: false,
    fullTitle: "Co-Buy a bag of rice",
    itemCost1: 0,
    visibility: 0,
    itemCost: 65000,
    splitCount: 3,
    privateGroup: false,
    userName: "Paul Adebayo",
    userId: "DXhnoPcO0LfmejgG5Be8kvugl9Y2",
    relevance: 0,
    mediaList: [
      {
        filePath:
          "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/YU8A2CLQPUbo?alt=media&token=2771b062-ac34-4c39-be45-1730a6925252",
        width: 297,
        id: "297170download (4).jpeg",
        type: "image",
        height: 170,
      },
      {
        filePath:
          "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/4l94m2rXEgoT?alt=media&token=2bd472b9-99f7-4d5f-8fce-08fa57af869e",
        width: 600,
        id: "600450rice-sack-production-company-600x450.jpg",
        type: "image",
        height: 450,
      },
    ],
    openJoin: false,
    categoryIcon:
      "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/c8267270-49c2-11ee-9221-f58405cc093b?alt=media&token=751d32b7-bc1c-49a8-9c4e-4a753608e39c",
    parties: [],
    setup: true,
    region: "akure",
    categoryId: "27e89a40-33b0-11ee-9ee7-bdbd733e67db",
    status: 1,
    createdAt: {
      _seconds: 1699247122,
      _nanoseconds: 383000000,
    },
    createdTime: {
      _seconds: 1699247122,
      _nanoseconds: 383000000,
    },
    reviewStart: {
      _seconds: 1699247122,
      _nanoseconds: 383000000,
    },
    updatedAt: {
      _seconds: 1699247122,
      _nanoseconds: 383000000,
    },
    id: "BtBnKShj6QzuxwxFSfpb",
    declinedRequest: [],
    joinRequest: [],
    inviteList: [],
    partiesCount: 1,
  },
];

export const catList = [
  {
    db: "categoryDb",
    id: "27e89a40-33b0-11ee-9ee7-bdbd733e67db",
    hintSamples: [
      "a bag of rice",
      "2 cartons of turkey",
      "40 tubers of yam",
      "a carton of butter",
      "3 bags of flour",
    ],
    tags: ["bulk purchase", "bulk buy", "group buy"],
    title: "Co-Buy",
    description: "Contribute with others and buy items in bulk",
    prefix: "",
    hint1: "What are you buying?",
    status: 1,
    hint2: "eg. Carton of Frozen Turkey",
    subCategories: [],
    priority: 1,
    costTitle: "Purchase Cost",
    icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/c8267270-49c2-11ee-9221-f58405cc093b?alt=media&token=751d32b7-bc1c-49a8-9c4e-4a753608e39c",
    keywords: ["Rice", "Shoe", "Turkey", "Foodstuff", "Groceries", "Cofee"],
  },
  {
    db: "categoryDb",
    hintSamples: [
      "an event space at Victoria Island",
      "a lawn mower",
      "a farm tractor",
      "a vehicle",
      "an apartment at Abuja",
    ],
    title: "Co-Rent",
    status: 1,
    subCategories: [],
    description: "Rent out spaces and equipment with others",
    costTitle: "Rent Cost",
    hint1: "What are you renting?",
    prefix: "",
    icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/f9606030-49c2-11ee-9221-f58405cc093b?alt=media&token=bc3628ce-854f-4b22-8467-14438a390f56",
    id: "41fd70d0-33c0-11ee-8260-3da8291766a7",
    hint2: "eg. A space for a workshop",
    priority: 2,
    keywords: ["Car", "Truck", "Tractor", "Mower", "Event Space", "Hall", "Mall"],
  },
  {
    keywords: [],
    description: "Split the cost of rides with others",
    priority: 3,
    status: 1,
    prefix: "to ",
    costTitle: "Transport Cost",
    subCategories: [],
    hint1: "Where are you going to?",
    hint2: "eg. Victoria island, Lagos",
    hintSamples: [
      "ShopRite at ikeja with Uber",
      "Douglas road in Owerri in a rented taxi",
      "FMC at Asaba with a rented car",
    ],
    icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/1a2a6360-49c3-11ee-9221-f58405cc093b?alt=media&token=7bdf248e-9eeb-4422-9855-00936f10ab1b",
    id: "417cb2a0-33c1-11ee-8260-3da8291766a7",
    title: "Co-Ride",
    db: "categoryDb",
  },
  {
    updatedAt: { seconds: 1699974053, nanoseconds: 419000000 },
    hintSamples: ["self-con at Surulere", "duplex at Lekki", "2 bedroom apartment at Owerri"],
    status: 1,
    keywords: ["Apartment", "Duplex", "Self Contain", "Bungalow"],
    title: "Co-Live",
    subCategories: [],
    hint2: "eg. 2 Bedroom flat at cele okota",
    icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/0a0febd0-49c3-11ee-9221-f58405cc093b?alt=media&token=05a38c61-26b2-4aaf-8c7f-eb3afb44d983",
    description: "Find a roommate and split cost of housing",
    prefix: "in a ",
    priority: 4,
    hint1: "What type of house and location?",
    costTitle: "Housing Cost",
    id: "a4d53e40-33c0-11ee-8260-3da8291766a7",
    db: "categoryDb",
  },
  {
    hint1: "What type subscription?",
    icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/27366270-49c3-11ee-9221-f58405cc093b?alt=media&token=b0df1973-e516-40a0-8d99-2e4cf98b0e4c",
    hint2: "eg. MTN 2 gig data plan",
    id: "895f1a40-33c1-11ee-8260-3da8291766a7",
    db: "categoryDb",
    description: "Share a subscription plan with someone",
    title: "Co-Subscribe",
    priority: 5,
    keywords: ["Data", "Airtime", "Internet"],
    costTitle: "Subscription Cost",
    hintSamples: ["MTN data plan", "Glo data bundle", "Airtel 5G bundle"],
    prefix: "to ",
    updatedAt: { seconds: 1699974056, nanoseconds: 191000000 },
    status: 1,
    tags: ["data plan", "cable plan", "subscription plan"],
    subCategories: [],
  },
  {
    status: 1,
    db: "categoryDb",
    costTitle: "Delivery Cost",
    title: "Co-Courier",
    priority: 6,
    description: "Jointly deliver items to persons in the same area",
    subCategories: [],
    updatedAt: { seconds: 1699974058, nanoseconds: 550000000 },
    keywords: ["Aba", "Lagos", "Kano", "Delta"],
    prefix: "items to ",
    hint2: "eg. Victoria Island, lagos",
    icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/379472b0-49c3-11ee-9221-f58405cc093b?alt=media&token=59d717c5-116e-41fe-b7b9-f9e49b7871c0",
    tags: ["waybill"],
    id: "521628c0-33c2-11ee-8260-3da8291766a7",
    hintSamples: ["Umuahia in Abia State", "Ikeja in Lagos"],
    hint1: "What is the delivery area?",
  },
];

// export const catList = [
//   {
//     hint1: "What are you buying?",
//     hint2: "eg. Carton of Frozen Turkey",
//     costTitle: "Purchase Cost",
//     prefix: "",
//     icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/c8267270-49c2-11ee-9221-f58405cc093b?alt=media&token=751d32b7-bc1c-49a8-9c4e-4a753608e39c",
//     description: "Contribute with others and buy items in bulk",
//     priority: 1,
//     title: "Co-Buy",
//     tags: ["Bulk Purchase", "Bulk Buys", "Group Buys"],

//     subCategories: [],
//     hintSamples: [
//       "a bag of rice",
//       "2 cartons of turkey",
//       "40 tubers of yam",
//       "a carton of butter",
//       "3 bags of flour",
//     ],
//     id: "27e89a40-33b0-11ee-9ee7-bdbd733e67db",
//     db: "categoryDb",
//     status: 1,
//   },
//   {
//     hint1: "What are you renting?",
//     hint2: "eg. A space for a workshop",
//     costTitle: "Rent Cost",
//     prefix: "",
//     icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/f9606030-49c2-11ee-9221-f58405cc093b?alt=media&token=bc3628ce-854f-4b22-8467-14438a390f56",
//     description: "Rent out a space or equipment with others",
//     priority: 2,
//     title: "Co-Rent",
//     tags: ["Group Rentals", "Equipment Rentals", "Hall Rentals"],
//     subCategories: [],
//     hintSamples: [
//       "an event space at Victoria Island",
//       "a lawn mower",
//       "a farm tractor",
//       "a vehicle",
//       "an apartment at Abuja",
//     ],
//     id: "41fd70d0-33c0-11ee-8260-3da8291766a7",
//     db: "categoryDb",
//     status: 1,
//   },
//   {
//     hint1: "What type of house and location?",
//     hint2: "eg. 2 Bedroom flat at cele okota",
//     costTitle: "Housing Cost",
//     prefix: "in a ",
//     icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/0a0febd0-49c3-11ee-9221-f58405cc093b?alt=media&token=05a38c61-26b2-4aaf-8c7f-eb3afb44d983",
//     description: "Share living space with others",
//     priority: 3,
//     title: "Co-Live",
//     tags: ["Roommate", "Flatmate", "Housemate"],
//     subCategories: [],
//     hintSamples: [
//       "self-con at Surulere",
//       "duplex at Lekki",
//       "2 bedroom apartment at Owerri",
//     ],
//     id: "a4d53e40-33c0-11ee-8260-3da8291766a7",
//     db: "categoryDb",
//     status: 1,
//   },
//   {
//     hint1: "Where are you going to?",
//     hint2: "eg. Victoria island, Lagos",
//     costTitle: "Ride Cost",
//     prefix: "to ",
//     icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/1a2a6360-49c3-11ee-9221-f58405cc093b?alt=media&token=7bdf248e-9eeb-4422-9855-00936f10ab1b",
//     description: "Share a ride with someone",
//     priority: 4,
//     title: "Co-Ride",
//     tags: ["Carpooling", "Ride Sharing", "Group Rides"],
//     subCategories: [],
//     hintSamples: [
//       "ShopRite at ikeja with Uber",
//       "Douglas road in Owerri in a rented taxi",
//       "FMC at Asaba with a rented car",
//     ],
//     id: "417cb2a0-33c1-11ee-8260-3da8291766a7",
//     db: "categoryDb",
//     status: 1,
//   },
//   {
//     hint1: "What type subscription?",
//     hint2: "eg. MTN 2 gig data plan",
//     costTitle: "Subscription Cost",
//     prefix: "to ",
//     icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/27366270-49c3-11ee-9221-f58405cc093b?alt=media&token=b0df1973-e516-40a0-8d99-2e4cf98b0e4c",
//     description: "Share a subscription plan with someone",
//     priority: 5,
//     title: "Co-Subscribe",
//     tags: ["Subscription Plans", "Data Plans", "Internet Plans"],
//     subCategories: [],
//     hintSamples: ["MTN data plan", "Glo data bundle", "Airtel 5G bundle"],
//     id: "895f1a40-33c1-11ee-8260-3da8291766a7",
//     db: "categoryDb",
//     status: 1,
//   },
//   {
//     hint1: "What is the delivery area?",
//     hint2: "eg. Victoria Island, lagos",
//     costTitle: "Delivery Cost",
//     prefix: "items to ",
//     icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/379472b0-49c3-11ee-9221-f58405cc093b?alt=media&token=59d717c5-116e-41fe-b7b9-f9e49b7871c0",
//     description: "Jointly deliver items to persons in the same area",
//     priority: 6,
//     title: "Co-Courier",
//     tags: ["Logistics", "Delivery", "Shipping"],
//     subCategories: [],
//     hintSamples: ["Umuahia in Abia State", "Ikeja in Lagos"],
//     id: "521628c0-33c2-11ee-8260-3da8291766a7",
//     db: "categoryDb",
//     status: 1,
//   },
// ];
// code to extract dummy list

// function startLoading() {
//   if (setup) return;
//   setSetup(true);
//   let dummyList = [];
//   // console.log(`${JSON.stringify(items)}`);
//   for (let i = 0; i < 100; i++) {
//     for (let index in items) {
//       let item = items[index];
//       let model = new SplitModel({ items: item });
//       let oldTime = model.getCreatedTime();
//       let days2 = 60 * 60 * 46 * 5;
//       let now = new Date(oldTime + days2);
//       let time = Timestamp.fromDate(now);
//       model.put("createdTime", time);
//       allItems.push(model);
//       if (i == 0) dummyList.push(model.items);
//     }
//   }
//   console.log(JSON.stringify(dummyList));
//   startTimer(pointer, currentItem);
// }
export const exampleList = [
  {
    title: "Co-Live",

    items: [
      {
        title: "Apartment",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/6b25dae0-0eb0-11ee-83fd-65faa3868739?alt=media&token=822341ed-6b03-4ad2-8fad-f06f93835ca7",
      },
      {
        title: "Co-living Space",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/1806dd00-0eb0-11ee-83fd-65faa3868739?alt=media&token=6536639a-335e-46e8-8f88-329fc10e7a1b",
      },
      {
        title: "Shared House",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/747e95f0-0eb0-11ee-83fd-65faa3868739?alt=media&token=8804a8de-e006-4ddc-932c-8e59c68c411d",
      },
      {
        title: "Student Dormitory",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/7bdd55c0-0eb0-11ee-83fd-65faa3868739?alt=media&token=b651f736-42d6-4a22-b24c-d1aed21ef0a4",
      },
      {
        title: "Workspace",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/80fd6cd0-1369-11ee-9735-5ba35a02e654?alt=media&token=14951ffc-0805-45dd-ae7e-0f4655fc5379",
      },
    ],
  },
  {
    title: "Co-Buy",

    items: [
      {
        title: "Baby Supplies",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/4e21e590-0e9e-11ee-895e-fd7979713406?alt=media&token=fdedd1bb-97e2-4d6a-951a-bc14e6e4d5c5",
      },
      {
        title: "Beverages",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/91db4780-0e9f-11ee-895e-fd7979713406?alt=media&token=7431b5cf-1c97-416a-883b-eed67cbecc97",
      },
      {
        title: "Groceries",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/3eafdfd0-0e9a-11ee-895e-fd7979713406?alt=media&token=73ade4a0-a088-4e2e-9298-f7ff1e15288a",
      },
      {
        title: "Household Essentials",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/d63fec50-0e9a-11ee-895e-fd7979713406?alt=media&token=9c7e61f5-94e4-43e2-bb90-81393e22ee40",
      },
      {
        title: "Office Supplies",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/458aad20-0e9b-11ee-895e-fd7979713406?alt=media&token=1a8b7a0a-518b-4dd5-bbfc-e0cb9893ccf1",
      },
      {
        title: "Paper Products",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/6b0eae90-0e9e-11ee-895e-fd7979713406?alt=media&token=e4968a4c-6cce-4ad5-92d8-991770bc47df",
      },
      {
        title: "Personal Care Products",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/7f52d2a0-0e9e-11ee-895e-fd7979713406?alt=media&token=a2270067-acb2-45aa-b17f-aa631f903beb",
      },
      {
        title: "Pet Supplies",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/5c67c430-0e9e-11ee-895e-fd7979713406?alt=media&token=031551be-ac07-48a6-b86a-971730191d72",
      },
      {
        title: "Snacks",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/ef201470-0e9f-11ee-895e-fd7979713406?alt=media&token=670158cc-6e9b-4978-8837-2c99b210578f",
      },
    ],
  },
  {
    title: "Co-Ride",
    tags: ["Carpool", "Ride Sharing", "Group Rides"],
    items: [
      {
        title: "Rental Car",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/4e4dcc00-0ea8-11ee-895e-fd7979713406?alt=media&token=ffc103d4-8f17-404a-830b-bba8a91f8b32",
      },
      {
        title: "Ride Services",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/a8799920-0ea8-11ee-895e-fd7979713406?alt=media&token=50ce510c-dca9-4417-acf5-98bf74b7030f",
      },
      {
        title: "Van",
        icon: "https://firebasestorage.googleapis.com/v0/b/splitamapp.appspot.com/o/b79f0250-0ea8-11ee-895e-fd7979713406?alt=media&token=2881bd85-5fb8-4e34-b118-648e3421c4a6",
      },
    ],
  },
];

export const testimonials = [
  {
    name: "Sunny Joe",
    title: "C.E.O Arkcess Technologies",
    photo: "t1.jpeg",
    message: "This platform has absolulety helped my with my spending",
  },
  {
    name: "Sola Fghanni",
    title: "C.E.O Crown DigitTech",
    photo: "p6.png",
    message: "If you hate paying the full fare for Uber rides, i think you're in the right place",
  },
  {
    name: "Minta Kwazu",
    title: "Founder Mintys Cakes",
    photo: "p3.png",
    message: "I love making bulk purchases cos it helps me buy more with less",
  },
  {
    name: "Agwu Iroha",
    title: "CTO MTR Techologies",
    photo: "t4.jpeg",
    message:
      "All i can say is this platform is brilliant, everything about the cost sharing is on point",
  },
];

export const costTypes = ["Fixed", "Range", "Unspecified"];

export const conjunctionsAndPrepositions = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "an",
  "and",
  "but",
  "or",
  "nor",
  "for",
  "yet",
  "so",
  "because",
  "although",
  "though",
  "since",
  "unless",
  "while",
  "when",
  "until",
  "if",
  "unless",
  "whether",
  "even though",
  "as",
  "in",
  "on",
  "at",
  "by",
  "with",
  "from",
  "to",
  "through",
  "into",
  "under",
  "over",
  "between",
  "among",
  "beside",
  "around",
  "after",
  "before",
  "during",
  "without",
  "behind",
  "near",
  "above",
  "below",
  "across",
  "among",
  "along",
  "amid",
  "concerning",
  "regarding",
  "beyond",
  "aboard",
  "about",
  "above",
  "across",
  "after",
  "against",
  "along",
  "among",
  "around",
  "as",
  "at",
  "before",
  "behind",
  "below",
  "beneath",
  "beside",
  "between",
  "beyond",
  "but",
  "by",
  "despite",
  "down",
  "during",
  "except",
  "failing",
  "following",
  "for",
  "from",
  "in",
  "inside",
  "into",
  "like",
  "minus",
  "near",
  "next",
  "of",
  "off",
  "on",
  "onto",
  "opposite",
  "out",
  "outside",
  "over",
  "past",
  "plus",
  "regarding",
  "since",
  "than",
  "through",
  "throughout",
  "till",
  "to",
  "toward",
  "towards",
  "under",
  "underneath",
  "unlike",
  "until",
  "up",
  "upon",
  "via",
  "with",
  "within",
  "without",
  "And",
  "Or",
  "But",
  "Nor",
  "So",
  "For",
  "Yet",
  "After",
  "Although",
  "As",
  "As If",
  "As Long As",
  "Because",
  "Before",
  "Even If",
  "Even Though",
  "If",
  "Once",
  "Provided",
  "Since",
  "So That",
  "That",
  "Though",
  "Till",
  "Unless",
  "Until",
  "What",
  "When",
  "Whenever",
  "Wherever",
  "Whether",
  "While",
];

export const cookie_data = {
  _gid: {
    Type: "First-party",
    Description:
      "This cookie is set by Google Analytics. It stores and updates a unique value for each page visited and is used to count and track pageviews.",
  },
  _ga: {
    Type: "First-party",
    Description:
      "This cookie name is associated with Google Universal Analytics - which is a significant update to Google's more commonly used analytics service. This cookie is used to distinguish unique users by assigning a randomly generated number as a client identifier. It is included in each page request in a site and used to calculate visitor, session, and campaign data for the site's analytics reports.",
  },
  uid: {
    Type: "First-party",
    Description:
      "This cookie provides a uniquely assigned, machine-generated user ID and gathers data about activity on the website. This data may be sent to a 3rd party for analysis and reporting.",
  },
  personalization_id: {
    Type: "Third-party",
    Description:
      "This cookie carries out information about how the end user uses the website and any advertising that the end user may have seen before visiting the said website.",
  },
  IDE: {
    Type: "Third-party",
    Description:
      "This cookie is set by Doubleclick and carries out information about how the end user uses the website and any advertising that the end user may have seen before visiting the said website.",
  },
  MUID: {
    Type: "Third-party",
    Description:
      "This cookie is widely used by Microsoft as a unique user identifier. It can be set by embedded Microsoft scripts. Widely believed to sync across many different Microsoft domains, allowing user tracking.",
  },
  ANONCHK: {
    Type: "Third-party",
    Description:
      "This cookie carries out information about how the end user uses the website and any advertising that the end user may have seen before visiting the said website.",
  },
  _gat_gtag_UA_137059257_1: {
    Type: "First-party",
    Description:
      "This cookie is part of Google Analytics and is used to limit requests (throttle request rate).",
  },
  CLID: {
    Type: "Third-party",
    Description:
      "This cookie is usually set by Dstillery to enable sharing media content to social media. It may also gather information on website visitors when they use social media to share website content from the page visited.",
  },
  test_cookie: {
    Type: "Third-party",
    Description:
      "This cookie is set by DoubleClick (which is owned by Google) to determine if the website visitor's browser supports cookies.",
  },
  SRM_B: {
    Type: "Third-party",
    Description:
      "This is a Microsoft MSN 1st party cookie that ensures the proper functioning of this website.",
  },
  _gcl_au: {
    Type: "First-party",
    Description:
      "Used by Google AdSense for experimenting with advertisement efficiency across websites using their services.",
  },
  SM: {
    Type: "Third-party",
    Description:
      "This is a Microsoft MSN 1st party cookie that we use to measure the use of the website for internal analytics.",
  },
  _fbp: {
    Type: "First-party",
    Description:
      "Used by Facebook to deliver a series of advertisement products such as real-time bidding from third-party advertisers.",
  },
  _ga_V7SNPVJK6G: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  rid: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  app: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  _clck: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  _clsk: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  _js2: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  app_sid: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  first_visit: {
    Type: "First-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
  muc_ads: {
    Type: "Third-party",
    Description: "Used by Splitam to facilitate website operation.",
  },
} as any;
